# Copyright (c) 2020 Huawei Technologies Co.,Ltd.
#
# openGauss is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
C1 = 'LOCK_CONTENTION'
C2 = 'MANY_DEAD_TUPLES'
C3 = 'FETCH_LARGE_DATA'
C4 = 'UNREASONABLE_DATABASE_KNOB'
C5 = 'REDUNDANT_INDEX'
C6 = 'UPDATE_LARGE_TABLE'
C7 = 'INSERT_LARGE_DATA'
C8 = 'DELETE_LARGE_DATA'
C9 = 'TOO_MANY_INDEX'
C10 = 'EXTERNAL_SORT'
C11 = 'VACUUM_EVENT'
C12 = 'ANALYZE_EVENT'
C13 = 'WORKLOAD_CONTENTION'
C14 = 'CPU_RESOURCE_CONTENTION'
C15 = 'IO_RESOURCE_CONTENTION'
C16 = 'MEMORY_RESOURCE_CONTENTION'
C17 = 'LARGE_NETWORK_DROP_RATE'
C18 = 'OS_RESOURCE_CONTENTION'
C19 = 'WAIT_EVENT'
C20 = 'LACK_STATISTIC_INFO'
C21 = 'MISSING_INDEXES'
C22 = 'POOR_JOIN_PERFORMANCE'
C23 = 'COMPLEX_BOOLEAN_EXPRESSIONS'
C24 = 'STRING_MATCHING'
C25 = 'COMPLEX_EXECUTION_PLAN'
C26 = 'CORRELATED_SUBQUERY'
C27 = 'POOR_AGGREGATION_PERFORMANCE'
C28 = 'ABNORMAL_SQL_STRUCTURE'
C29 = 'TIMED_TASK_CONFLICT'
C_UNKNOWN = 'C_UNKNOWN'
C_VIEW = 'DATABASE_VIEW'
C_SQL = 'ILLEGAL_SQL'
