CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K9_K10_K11_5_6_7_8] ON [dbo].[LINEITEM]
(
	[L_RETURNFLAG] ASC,
	[L_LINESTATUS] ASC,
	[L_SHIPDATE] ASC
)
INCLUDE ( 	[L_QUANTITY],
	[L_EXTENDEDPRICE],
	[L_DISCOUNT],
	[L_TAX]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K11_K1_4_6_7] ON [dbo].[LINEITEM]
(
	[L_SHIPDATE] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_LINENUMBER],
	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K1_K12_K13] ON [dbo].[LINEITEM]
(
	[L_ORDERKEY] ASC,
	[L_COMMITDATE] ASC,
	[L_RECEIPTDATE] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K3_K1_6_7] ON [dbo].[LINEITEM]
(
	[L_SUPPKEY] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K11_K7_K5_6] ON [dbo].[LINEITEM]
(
	[L_SHIPDATE] ASC,
	[L_DISCOUNT] ASC,
	[L_QUANTITY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K3_K11_K1_6_7] ON [dbo].[LINEITEM]
(
	[L_SUPPKEY] ASC,
	[L_SHIPDATE] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K2_K3_K1_6_7] ON [dbo].[LINEITEM]
(
	[L_PARTKEY] ASC,
	[L_SUPPKEY] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K1_2_3_5_6_7] ON [dbo].[LINEITEM]
(
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_PARTKEY],
	[L_SUPPKEY],
	[L_QUANTITY],
	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K9_K1_6_7] ON [dbo].[LINEITEM]
(
	[L_RETURNFLAG] ASC,
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K15_K13_K12_K11_K1] ON [dbo].[LINEITEM]
(
	[L_SHIPMODE] ASC,
	[L_RECEIPTDATE] ASC,
	[L_COMMITDATE] ASC,
	[L_SHIPDATE] ASC,
	[L_ORDERKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K11_K2_6_7] ON [dbo].[LINEITEM]
(
	[L_SHIPDATE] ASC,
	[L_PARTKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K2_K5_6] ON [dbo].[LINEITEM]
(
	[L_PARTKEY] ASC,
	[L_QUANTITY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K1_5] ON [dbo].[LINEITEM]
(
	[L_ORDERKEY] ASC
)
INCLUDE ( 	[L_QUANTITY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K3_K2_K11_5] ON [dbo].[LINEITEM]
(
	[L_SUPPKEY] ASC,
	[L_PARTKEY] ASC,
	[L_SHIPDATE] ASC
)
INCLUDE ( 	[L_QUANTITY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K15_K14_K5_K2_6_7] ON [dbo].[LINEITEM]
(
	[L_SHIPMODE] ASC,
	[L_SHIPINSTRUCT] ASC,
	[L_QUANTITY] ASC,
	[L_PARTKEY] ASC
)
INCLUDE ( 	[L_EXTENDEDPRICE],
	[L_DISCOUNT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_LINEITEM_5_1013578649__K3_K1_K13_K12] ON [dbo].[LINEITEM]
(
	[L_SUPPKEY] ASC,
	[L_ORDERKEY] ASC,
	[L_RECEIPTDATE] ASC,
	[L_COMMITDATE] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K5_1_2_8] ON [dbo].[ORDERS]
(
	[O_ORDERDATE] ASC
)
INCLUDE ( 	[O_ORDERKEY],
	[O_CUSTKEY],
	[O_SHIPPRIORITY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K5_K1_K6] ON [dbo].[ORDERS]
(
	[O_ORDERDATE] ASC,
	[O_ORDERKEY] ASC,
	[O_ORDERPRIORITY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K1_5] ON [dbo].[ORDERS]
(
	[O_ORDERKEY] ASC
)
INCLUDE ( 	[O_ORDERDATE]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K5_K1_K2] ON [dbo].[ORDERS]
(
	[O_ORDERDATE] ASC,
	[O_ORDERKEY] ASC,
	[O_CUSTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K1_6] ON [dbo].[ORDERS]
(
	[O_ORDERKEY] ASC
)
INCLUDE ( 	[O_ORDERPRIORITY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K2_K9] ON [dbo].[ORDERS]
(
	[O_CUSTKEY] ASC,
	[O_COMMENT] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_ORDERS_5_997578592__K4D_K5_1_2] ON [dbo].[ORDERS]
(
	[O_TOTALPRICE] DESC,
	[O_ORDERDATE] ASC
)
INCLUDE ( 	[O_ORDERKEY],
	[O_CUSTKEY]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K6_K5_K1_3] ON [dbo].[PART]
(
	[P_SIZE] ASC,
	[P_TYPE] ASC,
	[P_PARTKEY] ASC
)
INCLUDE ( 	[P_MFGR]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K5_K1] ON [dbo].[PART]
(
	[P_TYPE] ASC,
	[P_PARTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K2_K1] ON [dbo].[PART]
(
	[P_NAME] ASC,
	[P_PARTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K1_5] ON [dbo].[PART]
(
	[P_PARTKEY] ASC
)
INCLUDE ( 	[P_TYPE]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K6_K4_K5_K1] ON [dbo].[PART]
(
	[P_SIZE] ASC,
	[P_BRAND] ASC,
	[P_TYPE] ASC,
	[P_PARTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K6_K1_K4_K7] ON [dbo].[PART]
(
	[P_SIZE] ASC,
	[P_PARTKEY] ASC,
	[P_BRAND] ASC,
	[P_CONTAINER] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PART_5_933578364__K7_K4_K1] ON [dbo].[PART]
(
	[P_CONTAINER] ASC,
	[P_BRAND] ASC,
	[P_PARTKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_CUSTOMER_5_981578535__K7] ON [dbo].[CUSTOMER]
(
	[C_MKTSEGMENT] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_CUSTOMER_5_981578535__K1_K4] ON [dbo].[CUSTOMER]
(
	[C_CUSTKEY] ASC,
	[C_NATIONKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_CUSTOMER_5_981578535__K1_2] ON [dbo].[CUSTOMER]
(
	[C_CUSTKEY] ASC
)
INCLUDE ( 	[C_NAME]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_CUSTOMER_5_981578535__K6_K1_K5] ON [dbo].[CUSTOMER]
(
	[C_ACCTBAL] ASC,
	[C_CUSTKEY] ASC,
	[C_PHONE] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_CUSTOMER_5_981578535__K4_K1_2_3_5_6_8] ON [dbo].[CUSTOMER]
(
	[C_NATIONKEY] ASC,
	[C_CUSTKEY] ASC
)
INCLUDE ( 	[C_NAME],
	[C_ADDRESS],
	[C_PHONE],
	[C_ACCTBAL],
	[C_COMMENT]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PARTSUPP_5_965578478__K1_K2_4] ON [dbo].[PARTSUPP]
(
	[PS_PARTKEY] ASC,
	[PS_SUPPKEY] ASC
)
INCLUDE ( 	[PS_SUPPLYCOST]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PARTSUPP_5_965578478__K2_3_4] ON [dbo].[PARTSUPP]
(
	[PS_SUPPKEY] ASC
)
INCLUDE ( 	[PS_AVAILQTY],
	[PS_SUPPLYCOST]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_PARTSUPP_5_965578478__K2_K1_K3] ON [dbo].[PARTSUPP]
(
	[PS_SUPPKEY] ASC,
	[PS_PARTKEY] ASC,
	[PS_AVAILQTY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_SUPPLIER_5_949578421__K1_K4] ON [dbo].[SUPPLIER]
(
	[S_SUPPKEY] ASC,
	[S_NATIONKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_SUPPLIER_5_949578421__K4_K1] ON [dbo].[SUPPLIER]
(
	[S_NATIONKEY] ASC,
	[S_SUPPKEY] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];


CREATE NONCLUSTERED INDEX [_dta_index_SUPPLIER_5_949578421__K1_K7] ON [dbo].[SUPPLIER]
(
	[S_SUPPKEY] ASC,
	[S_COMMENT] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY];