{
 "title": "DBMind-forecasting",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  metric_time as time, metric_name, metric_value\nFROM tb_forecasting_metrics where metric_name='gaussdb_qps_by_instance' order by time;"
    }
   ]
  },
  {
   "title": "Disk iops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  metric_time as time, metric_value\nFROM tb_forecasting_metrics where metric_name='os_disk_iops' order by time;\n"
    }
   ]
  },
  {
   "title": "Responsetime Percentile p80",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  metric_time as time, metric_value\nFROM tb_forecasting_metrics where metric_name='statement_responsetime_percentile_p80' order by time;\n"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  metric_time as time, metric_name, metric_value\nFROM tb_forecasting_metrics where metric_name in ('os_mem_usage', 'os_cpu_usage', 'os_disk_usage') and pg_catalog.random() < 0.05 order by time;\n"
    }
   ]
  },
  {
   "title": "Future Alarms",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_at as time, *\nFROM tb_future_alarms\nORDER BY time desc, host;"
    }
   ]
  },
  {
   "title": "History Alarms",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurrence_at as time, * \nFROM tb_history_alarms order by time desc;"
    }
   ]
  }
 ]
}