{
 "title": "DBMind-index-advisor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Schemas of Databases",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select db_name, pg_catalog.count(1) from \n(SELECT\n    distinct on (host, db_name, schema_name) db_name, schema_name\nFROM tb_index_recommendation) \ngroup by db_name;"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct (host, db_name, schema_name, tb_name))\nFROM tb_index_recommendation;\n"
    }
   ]
  },
  {
   "title": "Improved Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  pg_catalog.avg(optimized)\nFROM tb_index_recommendation;"
    }
   ]
  },
  {
   "title": "SQL count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(stmt_count * select_ratio/100) as select_count, sum(stmt_count * update_ratio/100) as update_count,\n  sum(stmt_count * delete_ratio/100) as delete_count, sum(stmt_count * insert_ratio/100) as insert_count\nFROM tb_index_recommendation;\n"
    }
   ]
  },
  {
   "title": "Suggestions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  occurrence_time as time, sum(recommend_index_count) as advised_indexes, sum(invalid_index_count) as invalid_indexes, sum(redundant_index_count) as redundant_indexes  \nFROM tb_index_recommendation_stats group by occurrence_time;\n"
    }
   ]
  },
  {
   "title": "Advised Indexes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_index_recommendation;"
    }
   ]
  },
  {
   "title": "Invalid Indexes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n   *\nFROM tb_index_recommendation;"
    }
   ]
  },
  {
   "title": "Redundant Indexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_index_recommendation;"
    }
   ]
  },
  {
   "title": "Improved SQL",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  tb_index_recommendation_stmt_details.*\nFROM tb_index_recommendation_stmt_details"
    }
   ]
  },
  {
   "title": "Existing Indexes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_existing_indexes;"
    }
   ]
  }
 ]
}