{
 "title": "DBMind-recommendation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Database Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_knob_recommendation_metric_snapshot;"
    }
   ]
  },
  {
   "title": "Recommendation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_knob_recommendation_details;"
    }
   ]
  },
  {
   "title": "Recommendation Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM tb_knob_recommendation_warnings;"
    }
   ]
  }
 ]
}