{
 "title": "DBMind-regular-checking",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Daily Checking",
   "type": "logs",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n   report,start as time\nFROM tb_regular_inspections where inspection_type='daily check' order by time desc limit 1;"
    }
   ]
  },
  {
   "title": "Conclusion",
   "type": "logs",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  start as time, conclusion\nFROM tb_regular_inspections order by time desc limit 1;\n"
    }
   ]
  },
  {
   "title": "Month Statistics",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  date as time, * \nFROM tb_stat_one_month order by host, time;"
    }
   ]
  }
 ]
}